service: salve-dpp-backend

plugins:
  - serverless-offline

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs18.x
  environment:
    NODE_ENV: production

package:
  exclude:
    - deploy/**
  include:
    - node_modules/**

functions:
  main:
    handler: dist/server.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
